### PR TITLE
Add AmazonBasics HU9002V1SBL as a Supported Device

### PR DESCRIPTION
**Pull request by rjoleary**
Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

### CODE REVIEW

**Comment by mvp** [comment]
Thanks for your submission! Did you validate proper VBUS off? Does connected phone stop charging if port power is turned off?

**Comment by mvp** [comment]
Also, out of curiosity, can you please provide `sudo uhubctl` output for this hub? Basically, I'm interested in knowing actual USB topology of this hub - is this true 10 port chip, or 3*4port chips daisy chained together internally. Much thanks!

**Comment by rjoleary** [comment]
Yes, no problem! I'm thinking of using this USB hub to controller power to SF100 Dediprogs in a hardware test environment. The SF100 has a green power indicator which turns off when power is disconnected.

The hub is a 3*4 daisy chained. It shows up twice in uhubctl (I think this is because it's a 3.x hub):

```
Current status for hub 2-5.4.4 [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
Current status for hub 2-5.4 [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0503 power highspeed enable connect [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
Current status for hub 2-5 [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0503 power highspeed enable connect [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
```

```
Current status for hub 3-1.4.4 [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.10, 4 ports]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 3-1.4 [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.10, 4 ports]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 0243 power 5gbps U2 enable connect [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.10, 4 ports]
Current status for hub 3-1 [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.10, 4 ports]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 0243 power 5gbps U2 enable connect [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.10, 4 ports]
```

My devices being USB 2.x always show up on the USB2.x virtual hub and uhubctl seems to handle this gracefully.

**Comment by mvp** [comment]
Thanks for confirming VBUS off support and posting this device topology! I'm thinking to add separate column reflecting device topology to supported table (e.g. 3*4).

Yes, with 3*4 USB 3 hub you should see 6 hubs total, which may be slightly overwhelming :-)

It's a shame that manufacturers don't provide true high port count chips. Daisy chained hubs tend to work less reliably in my experience.

Good news is that more and more new hubs are starting to support per port power switching. I will probably remove that scary sentence about rarity of supported devices.

**Pull request merged**
