### PR TITLE
Support hubs with ganged power switching

### LINKED ISSUE #260: Allow uhubctl to run on incompatible hubs
First, thanks for this very useful tool!

If I'm not mistaken, currently uhubctl looks at the 'Per-port power switching' flag to decide if a hub is compatible. 

I'd like to suggest that uhubctl no longer refuses to operate on incompatible hubs, but merely outputs a warning. 

The reason is that from my experience, even if a hub does not support real power switching, it still does a port reset which usually triggers a reset of the attached USB device. And that's a useful feature. 

This 'port reset only' actually happens a lot. Right now, very often a hub has the 'Per-port power switching' flag set without actually really supporting it. In this case uhubctl will already trigger a port reset. Not perfect, but the best it can do! 

Why not allow this on all hubs?

Thanks!

### PR DESCRIPTION
**Pull request by henzef**
Tested on a D-Link DUB-H4 F-Revision hub.

This should fix #260 and #268

### CODE REVIEW

**Comment by mvp** [comment]
Thanks for effort, but sorry, I will not accept this. I have another set of patches in my queue which add command line force flag to enable operation on ganged hubs. I will be committing it soon.

**Comment by henzef** [comment]
Why do you want to hide it behind a flag? Not specifying -p should be enough, no?
And could you please keep this pr open till your solution is merged? I only found another (closed) pull request that does nearly the same *after* I implemented this ...

**Comment by mvp** [comment]
I understand your frustration. Main reason for this is that ganged hubs in general rarely work at all. I want users to specify extra flag if they really want to do it. By default, uhubctl should only show hubs with per-port power switching.

I will ping you here when it is implemented.

**Comment by mvp** [comment]
Implemented in 0cc0929.

**Pull request closed without merging**
