### PR TITLE
Add Beagleboard-xM to the Compatible USB hubs list

### PR DESCRIPTION
**Pull request by bertani**

### CODE REVIEW

**Comment by rleitner** [comment]
Hi,
the Hub isn't manufactured by Circuitco and the Product name isn't Beagleboard-xM (internal USB hub).

It should be the `SMC9514` by SMSC or `LAN9514` by Microchip.

Furthermore it should be discussed if we want to add the USB hub chips to the supported list or if we want to stay with "consumer products"...

**Comment by mvp** [comment]
From what I've seen, most (if not all) chipsets actually DO support PPPS (per-port power switching), which is needed for uhubctl to work. However, most chipsets allow OEM (like Anker, D-Link, etc) to configure them, in particular, to enable or disable PPPS. Some manufacturers don't even bother disabling PPPS on chipset level, they simply do not provide switching circuitry - PPPS appears to be enabled, but doesn't actually work.

With this in mind, listing chipsets would be a mistake.

Instead, we should list consumer products that can be easily purchased and used without modification. However, if some well known devices have internal (or onboard) USB hub, I see no issue listing them as compatible. For example, if some model of Raspberry PI supported it for internal root hub (and I have no idea if any model does), it would be fine to add it.

**Comment by bertani** [comment]
@rleitner indeed, most of the chipset I have tried so far do explicity declare PPPS support, but they really don't work due to missing wiring.

Other devices listed in the README are not strictly USB Hubs, but devices where the internal hub does support PPPS for real (for example the "Apple Thunderbolt Display 27" (internal USB hub)").

I find it valuable to keep it like it is, but maybe the name of the section could be changed from "Compatible USB hubs" to something more generic, like "Compatible USB hubs/devices". Note that USB hubs is accurate, as it doesn't refer to chipsets but to commercial devices.

**Comment by rleitner** [comment]
Ok. I see your point. I haven't thought of HW vendors who wire or configure their hubs incorrectly. So what do you think of adding another column for the hub chip used in those "well known" products?

**Comment by bertani** [comment]
@rleitner that could help, but most chipset declare PPPS support, so I don't see that being a valuable information as it all comes down to the wiring part. Anyway I am quite new to this so maybe @mvp can give us a more educated opinion :)

**Comment by mvp** [comment]
Sure, we can add such column. However, it can be sometimes difficult to find actual chipset vendor without taking device apart. Many people who report their findings only know model of their working device and perhaps where they purchased it. Worse still, some OEMs use different chipsets for different batches of exact same model :(

**Comment by SlySven** [comment]
From what I recall the internal USB HUBs on the Raspberry Pi (all types' "B" model variants) do not implement the switching hardware - which, given potentially battery operated end use cases keeps the price a tiny bit lower but IS a pity... :disappointed:

**Pull request merged**
