### PR TITLE
Add new device UNI Hub

### PR DESCRIPTION
**Pull request by niketh**
Here is the uhubctl output

```
uhubctl
Current status for hub 20-1 [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 5 ports]
  Port 1: 0103 power enable connect []
  Port 2: 0503 power highspeed enable connect []
  Port 3: 0503 power highspeed enable connect []
  Port 4: 0100 power
  Port 5: 0503 power highspeed enable connect []
Current status for hub 1-3 [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.10, 4 ports]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 0203 power 5gbps U0 enable connect []
  Port 4: 0203 power 5gbps U0 enable connect []
```

### CODE REVIEW

**Comment by mvp** [comment]
Few issues:

* You seem to be running uhubctl on MacOS Catalina with bad version of libusb 1.0.23. You need to use workaround listed here to install working libusb https://github.com/mvp/uhubctl#compiling
* We require that devices added to table must support VBUS off. Please test first if VBUS off is actually supported for this hub per https://github.com/mvp/uhubctl#how-do-i-check-if-my-usb-hub-is-supported-by-uhubctl
* You listed that this hub has 3 ports. However, your output shows that USB 2 device has 5 ports, and it's USB 3 counterpart has 4 ports. So, which one is it? Can you show manufacturer user guide or at least Amazon page for this product?
* You have to create pull request as single commit formatted similarly to other commits that add to the table. I can add them to table myself without your PR though.

**Comment by niketh** [comment]
1. Thanks for pointing the issues. I have updated `libusb`. Here is the new output
```
$ uhubctl
Current status for hub 20-1 [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 5 ports]
  Port 1: 0103 power enable connect [046d:c52b Logitech USB Receiver]
  Port 2: 0503 power highspeed enable connect [0458:6006 Vimicro corp. AUKEY PC-LM1E Camera AUKEY PC-LM1E Audio]
  Port 3: 0503 power highspeed enable connect [1a40:0801 USB 2.0 Hub]
  Port 4: 0100 power
  Port 5: 0503 power highspeed enable connect [2109:8888 VIA Labs, Inc. USB Billboard Device 0000000000000001]
Current status for hub 1-1 [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.10, 4 ports]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 0203 power 5gbps U0 enable connect [0bda:8153 Realtek USB 10/100/1000 LAN 000001]
  Port 4: 0203 power 5gbps U0 enable connect [05e3:0749 Generic USB3.0 Card Reader 000000001538]
```

2.  I cannot see the line `Per port power switching` when I run `sudo lsusb -v`. But 2nd test works for me. I plugged. in my phone and another video device. I use `sudo uhubctl -p 2  -n 2109:2817 -a 0` to turn off the device and my phone continues to charge and my video device is turned off as expected.

3. There are 2 USB 3.0, 1 USB 2.0, 2 USB C. Here is the [link](https://www.amazon.com/Ethernet-Adapter-uni-Detachable-Compatible/dp/B07Q6YS7W2/ref=asc_df_B07Q6YS7W2/?tag=hyprod-20&linkCode=df0&hvadid=362867004868&hvpos=&hvnetw=g&hvrand=2200034933475680993&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9032152&hvtargid=pla-782871990662&psc=1&tag=&ref=&adgrpid=81778694291&hvpone=&hvptwo=&hvadid=362867004868&hvpos=&hvnetw=g&hvrand=2200034933475680993&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9032152&hvtargid=pla-782871990662). 
4. I can squash or close the PR. Whatever is easier for you.

**Comment by mvp** [comment]
If your phone continues to charge even when port is off, it means VBUS off is not working as it should. We don't add such devices to the table.

**Comment by mvp** [comment]
And `sudo lsusb -v` is Linux specific, it will not work on Mac.

**Comment by niketh** [comment]
Maybe I didn't explain that well. I have 2 devices - phone and a video device. When i run `sudo uhubctl -p 2 -n 2109:2817 -a 0` to power off the video device - the video device powers off while my phone continues to charge. That is a desirable outcome and I assume you want such devices added to the list?

**Comment by mvp** [comment]
Most hubs will cut off data connection when you use uhubctl to turn port off. Cutting data connection will disconnect most devices like keyboard, mouse, flash drive, video devices, etc. However, that doesn't necessarily mean that USB is completely turned off as it _may_ still provide power to the bus (VBUS), and that will still let phone charge or USB light to shine.

If device doesn't support proper VBUS off (like yours), we don't consider them truly supported. Only devices which actually completely cut off power are currently added to supported devices table.

**Pull request closed without merging**
