### PR TITLE
Win32 build

### PR DESCRIPTION
**Pull request by apla**
Hi!

I've added the windows build with AppVeyor. C code now builds with VS2015, but little hairy.

Code builds with latest git version of libusb and this can be a problem, but you can easily add tag checkout. I would add the revision checkout, If not an issues with [windows hotplug](https://github.com/libusb/libusb/issues/86).

For each build you can download [binary executables](https://ci.appveyor.com/project/apla/uhubctl/build/1.0.12/artifacts)

Also it is possible to upload builds to github releases. I've added configuration template [as per docs](https://www.appveyor.com/docs/deployment/github/), but you should provide github key yourself.

I don't have smart hub at hand, so I cannot check whether port switch works or not, but device enumeration works ok.

### CODE REVIEW

**Comment by mvp** [comment]
Sorry, this simply doesn't work on Windows :(
I'm afraid the only way to fix this is wait until libusb starts supporting backend alternative to `winusb.sys`.

**Comment by apla** [comment]
I see. Seems like everyone «turning off» usb devices by disabling driver [like this](https://github.com/idmadj/handsoff/blob/master/DisableHardware.cs). Will you merge this pull request for the times when libusb will have it's own driver?

**Comment by mvp** [comment]
I don't think it makes much sense in merging this given that libusb supporting anything but winusb.sys may never happen.

I will add comment to README explaining why Windows is not supported, and what is needed to make it work.

**Comment by mvp** [comment]
I have merged your commit 39d30bdad33f6a2fe (with * 1000 fix), simplified ifdef mess d5cf8f882a3 and also added a note about winusb.sys limitations 15321d392.

Lets add AppVeyor stuff later, when libusb supports necessary control requests.
This should not require any changes to uhubctl.c - all Windows compatibility fixes are already in.

Thanks again for your help!

**Pull request closed without merging**
